FROM python:3.12-alpine AS pydantic-stage
WORKDIR /app
COPY /pydantic_models .
RUN pip install -r requirements.txt
RUN python3 rpg_models.py

FROM node:20-alpine AS final-stage
WORKDIR /app
COPY /backend .
COPY --from=pydantic-stage /app/models.pydantic ../pydantic_models/models.pydantic
#pydantic_models should be located next to the app itself
RUN yarn install
CMD ["sh", "-c", "yarn dev"]
